// Metadata card: chapters / titles + description / captions, generated by
// the local model (heuristic fallback offline). Chapters seek on click;
// everything is copyable; captions also download as .srt.

import { useState } from "react";
import { callTool } from "../ipc/api";
import { seekTo } from "../state/viewStore";

interface Chapter {
  title: string;
  start: number;
}

function fmt(t: number): string {
  const m = Math.floor(t / 60);
  const s = Math.floor(t % 60);
  return `${String(m).padStart(2, "0")}:${String(s).padStart(2, "0")}`;
}

function copy(text: string) {
  void navigator.clipboard?.writeText(text);
}

export function MetadataPanel({ projectId }: { projectId: string }) {
  const [busy, setBusy] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [chapters, setChapters] = useState<Chapter[] | null>(null);
  const [titles, setTitles] = useState<string[] | null>(null);
  const [description, setDescription] = useState<string | null>(null);
  const [srt, setSrt] = useState<string | null>(null);

  const run = async (kind: string, fn: () => Promise<void>) => {
    setBusy(kind);
    setError(null);
    try {
      await fn();
    } catch (err) {
      setError(String((err as { message?: string })?.message ?? err));
    } finally {
      setBusy(null);
    }
  };

  const genChapters = () =>
    run("chapters", async () => {
      const r = await callTool<{ chapters: Chapter[] }>("generate_chapters", {
        project_id: projectId,
      });
      setChapters(r.chapters);
    });

  const genTitles = () =>
    run("titles", async () => {
      const r = await callTool<{ titles: string[]; description: string }>(
        "generate_title_description",
        { project_id: projectId },
      );
      setTitles(r.titles);
      setDescription(r.description);
    });

  const genCaptions = () =>
    run("captions", async () => {
      const r = await callTool<{ srt: string }>("generate_captions", { project_id: projectId });
      setSrt(r.srt);
    });

  const downloadSrt = () => {
    if (!srt) return;
    const url = URL.createObjectURL(new Blob([srt], { type: "text/plain" }));
    const a = document.createElement("a");
    a.href = url;
    a.download = "captions.srt";
    a.click();
    URL.revokeObjectURL(url);
  };

  const chaptersText = (chapters ?? [])
    .map((c) => `${fmt(c.start)} ${c.title}`)
    .join("\n");

  return (
    <div className="metadata-card card">
      <h3 className="metadata-title">Metadata</h3>
      <div className="metadata-actions">
        <button className="meta-btn" disabled={!!busy} onClick={() => void genChapters()}>
          {busy === "chapters" ? "Generating…" : "Chapters"}
        </button>
        <button className="meta-btn" disabled={!!busy} onClick={() => void genTitles()}>
          {busy === "titles" ? "Generating…" : "Title & description"}
        </button>
        <button className="meta-btn" disabled={!!busy} onClick={() => void genCaptions()}>
          {busy === "captions" ? "Generating…" : "Captions"}
        </button>
      </div>
      {error && <p className="metadata-error">{error}</p>}

      {chapters && (
        <section className="metadata-section">
          <header>
            <span>Chapters · click to seek</span>
            <button className="copy-btn" onClick={() => copy(chaptersText)}>copy</button>
          </header>
          <ul className="chapter-list">
            {chapters.map((c, i) => (
              <li key={i} onClick={() => seekTo(c.start)}>
                <span className="chapter-time">{fmt(c.start)}</span> {c.title}
              </li>
            ))}
          </ul>
        </section>
      )}

      {titles && (
        <section className="metadata-section">
          <header>
            <span>Title ideas</span>
          </header>
          <ul className="title-list">
            {titles.map((t, i) => (
              <li key={i}>
                {t} <button className="copy-btn" onClick={() => copy(t)}>copy</button>
              </li>
            ))}
          </ul>
          {description && (
            <>
              <header>
                <span>Description</span>
                <button className="copy-btn" onClick={() => copy(description)}>copy</button>
              </header>
              <p className="metadata-description">{description}</p>
            </>
          )}
        </section>
      )}

      {srt !== null && (
        <section className="metadata-section">
          <header>
            <span>Captions ({(srt ?? "").split("\n\n").filter((b) => b.includes("-->")).length} cues, current cut)</span>
            <button className="copy-btn" onClick={() => copy(srt)}>copy</button>
            <button className="copy-btn" onClick={downloadSrt}>download .srt</button>
          </header>
        </section>
      )}
    </div>
  );
}
